sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 3164

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tQ8BP9zi2pCYct17PMQ
    access-key-secret: bMj3oAhy8FxP1xKWfzREuD5l6GiOl9
    bucket-name: lsl789