sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 3164

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com

    bucket-name: lsl789

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
